color: null
fieldLayouts:
  522bc6f4-f6fc-46b8-91fc-f043c7e06e82:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-06T22:04:14+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b79fe932-6803-451f-aca5-aef3cb20ec0c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-06T20:17:51+00:00'
            elementCondition: null
            fieldUid: 1b82b8f3-4af8-4c36-b32a-e6fda099c5f4 # Masthead
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd9ef7b1-5840-45d1-a221-69d06aeb859e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-06T20:17:51+00:00'
            elementCondition: null
            fieldUid: af5be94c-d29c-4ee3-b6d3-7d1990507e78 # Page Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91c81a93-f648-4f16-9427-b0727ed98863
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7a5f6e3a-f867-43e7-9636-fea1ca2694e4
        userCondition: null
handle: about
hasTitleField: true
icon: address-card
name: About
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
