color: null
fieldLayouts:
  a41dda54-d2b7-4c13-a650-b185100cd823:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-06T21:59:04+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d88e0ade-cef3-42e7-9cd0-9d73ca9047c7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-06T22:03:48+00:00'
            elementCondition: null
            fieldUid: 1b82b8f3-4af8-4c36-b32a-e6fda099c5f4 # Masthead
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b35746f-a7de-42ce-b6b0-e00704e48606
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-06T22:00:48+00:00'
            elementCondition: null
            fieldUid: af5be94c-d29c-4ee3-b6d3-7d1990507e78 # Page Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1f3aaa0-dcb0-4fa6-a1ea-4960d4673b02
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ed807824-3021-4151-89ec-d10747e1461e
        userCondition: null
handle: pages
hasTitleField: true
icon: memo
name: Pages
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
