defaultPlacement: end
enableVersioning: true
entryTypes:
  - bb1e742c-616e-46e8-b0f2-3086a0bb21bd # Home Page
handle: homePage
maxAuthors: 1
name: 'Home Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8f524a80-bce1-40a1-8940-aa11f17643fb: # brokenlinks
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
